### PR TITLE
It's Alive!

### PR DESCRIPTION
**Pull request by randytarampi**
It's Alive!

I really didn't know what else to title this PR, but it seemed appropriate.

I needed something that did what this project set out to do, so I actually fixed it. In retrospect, I probably should've just written something totally from scratch but here I am. This certainly looked like a better solution than standing up an [entire CloudFormation stack](https://github.com/widdix/aws-s3-virusscan), so I stuck with it.

This isn't something that I need to get merged in to use personally, but I really don't want to build too much out on a non `master` branch, especially since this seems to be a great place to merge things back in. I can see that the original author of this repository is no longer with this organization, but I'm hoping that someone over there can merge this in so I'm not spinning a bunch of branches off this `get-this-working` one.

### CODE REVIEW

**Comment by oyeanuj** [comment]
@urg Can this be merged?

@randytarampi Thank you! Is this available on a fork that one case test with?

**Comment by randytarampi** [comment]
@oyeanuj Yeah, the [branch for this PR still exists](https://github.com/randytarampi/slamscan/tree/get-this-working) though you'll need to follow the setup instructions as there are a few bits that aren't included.

There's even a different [branch that picks up SNS triggers](https://github.com/randytarampi/slamscan/tree/process-sns-triggers), which is my actual use case.

**Comment by urg** [comment]
@jjhoyt - who's the best person at PeerJ to consider this one?

**Comment by urg** [comment]
Congrats @randytarampi for getting it working :)

**Comment by jjhoyt** [comment]
> who's the best person at PeerJ to consider this one?

@c-cooperjones or @michaelstoner

**Pull request merged**
